resolution: [1280, 720]

sources:
    - webcam:
        type: v4l2
        device: /dev/video0
    - test:
        type: test

mixers:
    - TestA:
        sources:
            - test
            - webcam
        mixes:
            - Webcam/Test alpha blend:
                - webcam:
                    alpha: 0.5
            - Webcam/Test picture-in-picture:
                - webcam:
                    alpha: 0.8
                    width: 320
                    height: 180
                    x: 960
                    y: 540
            - Webcam Only
            - Test Only:
                - webcam:
                    alpha: 0
    - TestB:
        sources:
            - test
        mixes:
            - Test
            - Test alpha:
                - webcam:
                    alpha: 0.5
