resolution: [1280, 720]
framerate: 30/1

sources:
    - webcam:
        type: decklink
        device: 0
        mode: 14
        connection: hdmi
    - test:
        type: test
    - mic:
        type: pulse

mixers:
    - TestA:
        sources:
            - test
            - webcam
        mixes:
            - Webcam/Test alpha blend:
                - webcam:
                    alpha: 0.5
            - Webcam/Test picture-in-picture:
                - webcam:
                    alpha: 0.8
                    width: 320
                    height: 180
                    x: 960
                    y: 540
            - Webcam Only
            - Test Only:
                - webcam:
                    alpha: 0
#        outputs:
#            - udp:
#                host: 224.10.99.1
#                port: 6473
#                audio: yes
    - TestB:
        sources:
            - test
        mixes:
            - Test
            - Test alpha:
                - webcam:
                    alpha: 0.5
